### ISSUE TITLE
Searching Spell Effects / Aura Names Bug

### ISSUE THREAD

**Issue by Variona** [stoneharry/WoW-Spell-Editor#234]
**Spell editor version**
v2.2.2

**Describe the bug**
It seems that whenever I try and use the search feature it bugs out by applying the value to every spell entry? Not evenly, some just seem to tag the entry on. Perhaps if its a valid entry? I'm not sure.

**To Reproduce**
1. Go to any spell
2. Navigate to and effects tab
3. Select a drop down box that allows you to insert text or numbers to search.
4. Use the search feature to select a spell effect / apply aura name
5. Save the spell changes
6. Go to any other spell
7. Check if that spell has had its effect / aura name changed as well.

**Expected behavior**
Changing the spell effect or aura name should only affect the spell you are currently editing.

**Additional context**
[Quick video I took of the issue.](https://www.youtube.com/watch?v=d8k6G8YbcrE)

OBS doesn't seem to capture the dropdown menus for some reason.

**Comment by stoneharry** [comment]
I think this is fixed with v2.2.3. Are you able to test again with the new version please?

**Comment by stoneharry** [comment]
I think it should be resolved. You may need to dismiss any exception, resave the spell, then it should work after that.

**Comment by Variona** [comment]
> I think it should be resolved. You may need to dismiss any exception, resave the spell, then it should work after that.

I'm not getting any exceptions. Its still doing the same issue as I described above.

**Comment by stoneharry** [comment]
I'm able to reproduce. It seems to be a display only bug, if you restart the program they all show the correct value. Let me look into it.

**Comment by stoneharry** [comment]
Fixed in 87a3b3bc212c3ec2175991d0cd4583b53494393d

I'll leave this open to track the issue until a new version is published.

**Comment by stoneharry** [comment]
New version is published, please give it a test.

**Comment by Variona** [comment]
It seems better. The very first time I switch away from the spell I edited the newly selected spell still has the bug. But if I switch to a new spell once again it fixes itself. Better than having to restart the program but still not fully fixed.

**Comment by stoneharry** [comment]
This is fixed in the latest release (v2.2.5 as of this post).
